site_name: Address Parsing
docs_dir: src-addresses
site_dir: dist-addresses
extra_css: [css/codehilite/mapzen.css]

pages:
  - Home: index.md

extra:
  site_subtitle: 'Parse and expand address data with the libpostal engine.'
  project_repo_url: https://github.com/whosonfirst/go-whosonfirst-libpostal
  docs_base_url: https://github.com/whosonfirst/go-whosonfirst-libpostal/blob/master/docs
