site_name: Mapzen Android SDK
docs_dir: src-android
site_dir: dist-android

pages:
  - Home: index.md
  - 'Installation': 'installation.md'
  - 'Get started': 'getting-started.md'
  - 'Position, rotation, and zoom': 'basic-functions.md'
  - 'Add features': 'features.md'
  - 'Switching styles': 'styles.md'
  - 'Gesture responders': 'gesture-responders.md'
  - 'Location services': 'location-services.md'
  - 'Mapzen Places API': 
    - 'Overview': 'places.md'
    - 'Autocomplete interface': 'autocomplete-ui.md'
    - 'GeoData API': 'geodata-api.md'
  - 'Mapzen Search for Android': 'search.md'
  - 'Mapzen Turn-by-Turn for Android': 'turn-by-turn.md'
 
extra:
  site_subtitle: 'A thin wrapper that packages up everything you need to use Mapzen services in your Android applications.'
  project_repo_url: https://github.com/mapzen/android
  docs_base_url: https://github.com/mapzen/android/tree/master/docs
