site_name: Mapzen iOS SDK
docs_dir: src-ios
site_dir: dist-ios

pages:
  - Home: index.md
  - 'Installation': 'installation.md'
  - 'Get started': 'getting-started.md'
  - 'Position, rotation, and zoom': 'basic-functions.md'
  - 'Add features': 'features.md'
  - 'Switching styles': 'styles.md'
  - 'Gestures': 'gesture-delegates.md'
  - 'Location Services': 'location-services.md'
  - 'Mapzen Places for iOS': 'places.md'
  - 'Mapzen Search for iOS': 'search.md'
  - 'Mapzen Turn-by-Turn for iOS': 'turn-by-turn.md'
  - 'Documentation': 'documentation.md'

extra:
  site_subtitle: 'A thin wrapper that packages up everything you need to use Mapzen services in your iOS applications.'
  project_repo_url: https://github.com/mapzen/ios
  docs_base_url: https://github.com/mapzen/ios/tree/master/docs
