site_name: Mapzen Mobility
docs_dir: src-mobility
site_dir: dist-mobility

pages:
  - Home: index.md
  - 'Glossary': 'terminology.md'
  - Turn-by-Turn:
    - 'Overview': 'turn-by-turn/overview.md'
    - 'API reference': 'turn-by-turn/api-reference.md'
    - 'Tutorial': 'turn-by-turn/add-routing-to-a-map.md'
  - 'Optimized route': 'optimized/api-reference.md'
  - 'Time-Distance Matrix': 'matrix/api-reference.md'
  - 'Isochrone': 'isochrone/api-reference.md'
  - 'Map Matching': 'map-matching/api-reference.md'
  - 'Mobility Explorer':
    - 'Overview': 'explorer/overview.md'
    - 'Explore transit': 'explorer/explore-transit.md'
    - 'Generate isochrones': 'explorer/isochrones.md'
    - 'Match GPS locations to a route': 'explorer/map-matching.md'
    - 'Tutorial': 'explorer/tutorial.md'
  - 'Reference':
    - 'Speeds': 'speeds.md'
    - 'Decode a route shape': 'decoding.md'
  - 'Release notes': 'release-notes.md'

mz:redirects:
  'turn-by-turn': 'turn-by-turn/api-reference'
  'matrix': 'matrix/api-reference'
  'optimized': 'optimized/api-reference'
  'isochrone': 'isochrone/api-reference.md'
  'map-matching': 'map-matching/api-reference.md'

extra:
  site_subtitle: 'Add routing and navigation to your web and mobile apps.'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/valhalla/valhalla-docs/tree/master

# force refresh
