site_name: Developer overview
docs_dir: src-overview
site_dir: dist-overview

pages:
  - Overview: index.md
  - 'Account settings': 'account-settings.md'
  - 'Billing information': 'billing.md'
  - 'API keys': 'api-keys.md'
  - 'Contact support': 'support.md'

extra:
  site_subtitle: Get started developing with Mapzen's products
  project_repo_url: https://github.com/mapzen/mapzen-docs-generator
  docs_base_url: https://github.com/mapzen/mapzen-docs-generator/tree/master/docs/overview/
  exclude_home_contents_in_toc: false
