site_name: Tangram
docs_dir: src-tangram-new
site_dir: dist-tangram

# Because Tangram does not organize documentation in folders, we're going to have
# to enforce the Table of Contents structure manually in the configuration below.
# This means pages should be added or subtracted manually here if the files change.
pages:
  - Get Started: index.md
    - 'Tangram Basics': index.md
  - Documentation:
    - 'The scene file': 'scene-file.md'
    - 'Data': 'data.md'
    - 'Styling features': 'styles-overview.md'
    - 'Editing map view': 'map-view.md'
    - 'Shaders': 'shaders-overview.md'
  - 'API Reference': 'api-reference.md'
  - Tutorials:
    - 'Make a Tangram map': 'intro-tutorial.md'
    - 'Cartographic design': 'cartography.md'
    - 'Editing a basemap': 'basemap.md'
    - 'Custom Styles': 'custom-styles.md'
    - 'Terrain maps': 'terrain.md'
  - 'Gallery': 'gallery.md'

mz:redirects:
  'tangram-overview': '.'
  'filters-overview': 'data'
  'raster-overview': 'styles-overview#rasters'
  'lights-overview': 'map-view#lights'
  'cameras-overview': 'map-view#cameras'
  'materials-overview': 'styles-overview#materials'
  'yaml': 'index#yaml'
  'cameras': 'map-view#cameras'
  'draw': 'styles-overview#draw'
  'global': 'scene-file#global'
  'fonts': 'styles-overview#fonts'
  'import': 'data#import'
  'layers': 'data#layers'
  'lights': 'map-view#lights'
  'materials': 'styles-overview#materials'
  'scene': 'scene-file'
  'shaders': 'shaders-overview'
  'sources': 'data#sources'
  'styles': 'styles-overview'
  'textures': 'styles-overview#textures'
  'javascript-api': 'api-reference'
  'Android-API': 'api-reference#android'
  'demos': 'gallery'
  'walkthrough': 'intro-tutorial'
  # 'Android Walkthrough': 'android-walkthrough.md' (NEED TO REDIRECT BUT WHERE TO PUT THIS???)

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: false

# Extra variables for templates
extra:
  site_subtitle: Render 2D and 3D maps with fine control over almost every aspect of the map making process.
  project_repo_url: https://github.com/tangrams/tangram
  docs_base_url: https://github.com/tangrams/tangram-docs/tree/gh-pages/pages
  exclude_home_contents_in_toc: false
