site_name: Tangram
docs_dir: src-tangram-new
site_dir: dist-tangram

# Because Tangram does not organize documentation in folders, we're going to have
# to enforce the Table of Contents structure manually in the configuration below.
# This means pages should be added or subtracted manually here if the files change.
pages:
  - Home: index.md
  - Concept Overviews:
    - 'Tangram': 'Tangram-Overview.md'
    - 'The Scene File': 'Scene-file.md'
    - 'Data Filters': 'Filters-Overview.md'
    - 'Styles': 'Styles-Overview.md'
    - 'Shaders': 'Shaders-Overview.md'
    - 'Raster Sources': 'Raster-Overview.md'
    - 'Lights': 'Lights-Overview.md'
    - 'Cameras': 'Cameras-Overview.md'
    - 'Materials': 'Materials-Overview.md'
    - 'YAML': 'yaml.md'
  - Syntax Reference:
    - 'cameras': 'cameras.md'
    - 'draw': 'draw.md'
    - 'global': 'global.md'
    - 'fonts': 'fonts.md'
    - 'import': 'import.md'
    - 'layers': 'layers.md'
    - 'lights': 'lights.md'
    - 'materials': 'materials.md'
    - 'scene': 'scene.md'
    - 'shaders': 'shaders.md'
    - 'sources': 'sources.md'
    - 'styles': 'styles.md'
    - 'textures': 'textures.md'
  - JavaScript API: 'Javascript-API.md'
  - Android API: 'Android-API.md'
  - iOS API: 'iOS-API.md'
  - Demos & Examples:
    - 'Demos': 'Demos.md'
    - 'JS Walkthrough': 'walkthrough.md'
    - 'Android Walkthrough': 'android-walkthrough.md'

mz:redirects:
  'tangram-overview': '.'
  'filters-overview': 'data'
  'raster-overview': 'styles-overview#rasters'
  'lights-overview': 'map-view#lights'
  'cameras-overview': 'map-view#cameras'
  'materials-overview': 'styles-overview#materials'
  'yaml': 'index#yaml'
  'cameras': 'map-view#cameras'
  'draw': 'styles-overview#draw'
  'global': 'scene-file#global'
  'fonts': 'styles-overview#fonts'
  'import': 'data#import'
  'layers': 'data#layers'
  'lights': 'map-view#lights'
  'materials': 'styles-overview#materials'
  'scene': 'scene-file'
  'shaders': 'shaders-overview'
  'sources': 'data#sources'
  'styles': 'styles-overview'
  'textures': 'styles-overview#textures'
  'javascript-api': 'api-reference'
  'Android-API': 'api-reference#android'
  'demos': 'gallery'
  'walkthrough': 'intro-tutorial'
  # 'Android Walkthrough': 'android-walkthrough.md' (NEED TO REDIRECT BUT WHERE TO PUT THIS???)

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: false

# Extra variables for templates
extra:
  site_subtitle: Render 2D and 3D maps with fine control over almost every aspect of the map making process.
  project_repo_url: https://github.com/tangrams/tangram
  docs_base_url: https://github.com/tangrams/tangram-docs/tree/gh-pages/pages
