site_name: Tutorials
docs_dir: src-tutorials
site_dir: dist-tutorials

pages:
  - Overview: index.md
  - Text editors: install-text-editor.md
  - Server environment: server-environment.md

extra:
  site_subtitle: Set up your development environment with these tips and tricks
  project_repo_url: https://github.com/mapzen/mapzen-docs-generator
  docs_base_url: https://github.com/mapzen/mapzen-docs-generator/tree/master/docs
