site_name: Who's On First API
docs_dir: src-wof
site_dir: dist-wof

pages:
  - Home: index.md
  - 'Formats': 'formats.md'
  - 'Methods': 'methods.md'
  - 'Pagination': 'pagination.md'
  - 'Error codes': 'errors.md'

extra:
  site_subtitle: 'Retrieve data about places from our gazetteer, Who's On First.'
  project_repo_url: https://github.com/whosonfirst/whosonfirst-www-api
  docs_base_url: https://github.com/whosonfirst/whosonfirst-www-api/tree/master/docs
  exclude_home_contents_in_toc: false
